#!/bin/bash

#PBS -N gapfiller.115c.sub
#PBS -q fnrgenetics
#PBS -l nodes=1:ppn=16
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

# cat copies the command file to the output
cat gapfiller.sub

date +"%d %B %Y %H:%M:%S"
echo ""

module use /apps/group/bioinformatics/modules
module load GapFiller
module load perl

cd /scratch/carter/j/jwillou/Mono/gapfiller30/gapfiller30_115cleaned

GapFiller.pl \
-l /scratch/carter/j/jwillou/Mono/sspacelibrary.txt \
-s /scratch/carter/j/jwillou/Mono/sspace30_scaffolds/monpu30_115cleaned/monpu30_115.final.scaffolds.fasta \
-m 135 \
-T 15 \
-b last.cleaned.115 \
&> gapfiller115.log\

echo ""
date +"%d %B %Y %H:%M:%S"


 








