#!/usr/bin/perl -w

#PBS -N fq2fa.sub
#PBS -q standby
#PBS -l nodes=1:ppn=1
#PBS -l walltime=04:00:00


#Converts fastq to fasta

chdir '/scratch/carter/j/jwillou/Mono';

my $file = "rnaseq-forward-pairedv2.fq";
my $outfile = "rnaseq-forward-pairedv2.fa";
open (INFILE, "<", $file);
open (OUTFILE, ">", $outfile);

my $i = 1;
while(my $line = <INFILE>){
	if($i % 4 == 1){
		$line =~ s/\@/\>/;
		print OUTFILE $line;
	}elsif($i % 4 == 2){
		print OUTFILE $line;
	}elsif($i % 4 == 3){
	}elsif($i % 4 == 0){
	}else{
		print "Modulo error.";	
	}
	$i++;
}

close INFILE;
close OUTFILE;

exit 0;
