#!/bin/bash

#PBS -N minia35cleaned
#PBS -q scholar
#PBS -l nodes=1:ppn=16
#PBS -l walltime=36:00:00
#PBS -m abe
#PBS -M jwillou@purdue.edu

cd $PBS_O_WORKDIR

module use /apps/group/bioinformatics/modules
module load minia

#Running minia on cleaned reads with kmer size of 35
#genome size from kmer estimation
minia /scratch/carter/j/jwillou/Mono/monpu.noadapt.nomatch.all.30.fa 31 5 26000000 miniakmer31 &> miniakmer31.log
