#!/bin/bash

#PBS -N minia115cleaned
#PBS -q fnrgenetics
#PBS -l nodes=1:ppn=16
#PBS -l walltime=36:00:00
#PBS -m abe
#PBS -M jwillou@purdue.edu

cd $PBS_O_WORKDIR
cd /scratch/carter/j/jwillou/Mono/minia30ass/kmer115

module use /apps/group/bioinformatics/modules
module load minia/maxk128

#Running minia on cleaned reads with kmer size of 115
#genome size from kmer estimation
minia /scratch/carter/j/jwillou/Mono/monpu.noadapt.nomatch.all.30.fa 115 5 26000000 miniakmer115 &> miniakmer115.log
