#!/bin/sh -l

#PBS -N trimm_mon
#PBS -q scholar
#PBS -l nodes=1:ppn=16
#PBS -l walltime=04:00:00

module load trimmomatic
module load java

cd $PBS_O_WORKDIR

trimmomatic PE -phred33 \
Monpu1.genome.rawReads.r1.fq \
Monpu1.genome.rawReads.r2.fq \
trimm.pairedout.r1.30.fq \
trimm.unpairedout.r1.30.fq \
trimm.pairedout.r2.30.fq \
trimm.unpairedout.r2.30.fq \
ILLUMINACLIP:illumina.fa:2:30:10 \
LEADING:15 \
TRAILING:15 \
SLIDINGWINDOW:3:20 \
MINLEN:30
